baseurl = "https://woodyzootopia.github.io"
languageCode = "ja-JP"
title = "うっでぃの雑記帳"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-114969766-2"
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"
# Comment the themesDir option if you use this theme in production
#themesDir = "../.."
enableGitInfo = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[permalinks]
    post = "/:year/:month/:slug"


[params]

    # Tell me who you are
    author = "Woody"
    bio = "Memento mori"
    location = "Waterloo, Ontario"
    site_description = "カナダ留学中の大学生が徒然なるままに書き綴ります。備忘録・技術記事・日常の記録など"
    copyright  = "Licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) for my own creation"
    avatar = "/img/midna2.jpg"
    # Enter your email address to display your Gravatar icon in the profile. If not set the theme
    # will fallback to the avatar.
    #gravatar = "you@example.com"
    logo = "css/images/logo.jpg"
    disable_mathjax = false # set to true to disable MathJax

    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["post"]

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	custom_css = []
	# custom_js  = ['javascript/mathjax-markdown-solution.js']

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = true
    label  = "About"
    link   = "main/about/"

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://twitter.com/woody_egg"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "woodyZootopia"
    gitlab          = "woodyZootopia"
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "shu-nakamura-208215170"
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = "ShuWoodyNak"
    facebook_admin  = ""
    twitter         = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = false
    categories = true
    tags = true
    tag_cloud = true
